[package]
name = "example"
version = "0.1.0"
authors = ["Dgame <rswhite4@googlemail.com>"]
edition = "2018"

[dependencies]
serde_conv_derive = { path = "../serde_conv_derive" }
serde_conv = { path = "../serde_conv" }
serde = "1.0.90"
serde_derive = "1.0.90"
serde_json = "1.0.39"
