[package]
name = "serde_conv_derive"
version = "0.1.0"
authors = ["Dgame <rswhite4@googlemail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "0.6.11"
proc-macro2 = "0.4.27"
paste = "0.1.5"

[dependencies.syn]
version = "0.15.29"
features = ["full"]
